---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app-local
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: applications/app1
    repoURL: https://github.com/reddymanjesh/argocd.git
    targetRevision: HEAD
  destination:
    namespace: default
    server: https://kubernetes.default.svc